export const GESTURE = {
  NONE: 'none',
  FIST: 'fist',
  POINTER: 'pointer',
  PEACE: 'peace',
  OPEN_PALM: 'open_palm',
  THUMBS_UP: 'thumbs_up',
  THUMBS_DOWN: 'thumbs_down',
  OK: 'ok',
  LOVE: 'love',
  ROCK: 'rock',
  WAVE: 'wave',
  DRAW: 'draw',
  PINCH: 'pinch',
  THREE: 'three',
  FOUR: 'four',
}

export const GESTURE_LABELS = {
  [GESTURE.NONE]: 'No Gesture',
  [GESTURE.FIST]: 'Fist',
  [GESTURE.POINTER]: 'Pointer',
  [GESTURE.PEACE]: 'Peace',
  [GESTURE.OPEN_PALM]: 'Open Palm',
  [GESTURE.THUMBS_UP]: 'Thumbs Up',
  [GESTURE.THUMBS_DOWN]: 'Thumbs Down',
  [GESTURE.OK]: 'OK',
  [GESTURE.LOVE]: 'Love',
  [GESTURE.ROCK]: 'Rock',
  [GESTURE.WAVE]: 'Wave',
  [GESTURE.DRAW]: 'Draw',
  [GESTURE.PINCH]: 'Pinch',
  [GESTURE.THREE]: 'Three',
  [GESTURE.FOUR]: 'Four',
}

export const GESTURE_EMOJIS = {
  [GESTURE.NONE]: '',
  [GESTURE.FIST]: '✊',
  [GESTURE.POINTER]: '☝️',
  [GESTURE.PEACE]: '✌️',
  [GESTURE.OPEN_PALM]: '🖐️',
  [GESTURE.THUMBS_UP]: '👍',
  [GESTURE.THUMBS_DOWN]: '👎',
  [GESTURE.OK]: '👌',
  [GESTURE.LOVE]: '🤟',
  [GESTURE.ROCK]: '🤘',
  [GESTURE.THREE]: '3️⃣',
  [GESTURE.FOUR]: '4️⃣',
  [GESTURE.WAVE]: '👋',
  [GESTURE.DRAW]: '✍️',
  [GESTURE.PINCH]: '🤏',
}
